<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WebsiteTbSecurityUserDescription extends \Application\Entity\WebsiteTbSecurityUserDescription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'susiId', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvName', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvLastname', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudiCreatedBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'suddCreatedDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvCreatedIp', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudiModBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'suddModDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvModIp');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'susiId', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvName', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvLastname', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudiCreatedBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'suddCreatedDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvCreatedIp', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudiModBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'suddModDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityUserDescription' . "\0" . 'sudvModIp');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WebsiteTbSecurityUserDescription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSusiId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSusiId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSusiId', array());

        return parent::getSusiId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSudvName($sudvName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSudvName', array($sudvName));

        return parent::setSudvName($sudvName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSudvName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSudvName', array());

        return parent::getSudvName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSudvLastname($sudvLastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSudvLastname', array($sudvLastname));

        return parent::setSudvLastname($sudvLastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSudvLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSudvLastname', array());

        return parent::getSudvLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSudiCreatedBy($sudiCreatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSudiCreatedBy', array($sudiCreatedBy));

        return parent::setSudiCreatedBy($sudiCreatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getSudiCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSudiCreatedBy', array());

        return parent::getSudiCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuddCreatedDate($suddCreatedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuddCreatedDate', array($suddCreatedDate));

        return parent::setSuddCreatedDate($suddCreatedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuddCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuddCreatedDate', array());

        return parent::getSuddCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSudvCreatedIp($sudvCreatedIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSudvCreatedIp', array($sudvCreatedIp));

        return parent::setSudvCreatedIp($sudvCreatedIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getSudvCreatedIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSudvCreatedIp', array());

        return parent::getSudvCreatedIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSudiModBy($sudiModBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSudiModBy', array($sudiModBy));

        return parent::setSudiModBy($sudiModBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getSudiModBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSudiModBy', array());

        return parent::getSudiModBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuddModDate($suddModDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuddModDate', array($suddModDate));

        return parent::setSuddModDate($suddModDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuddModDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuddModDate', array());

        return parent::getSuddModDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSudvModIp($sudvModIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSudvModIp', array($sudvModIp));

        return parent::setSudvModIp($sudvModIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getSudvModIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSudvModIp', array());

        return parent::getSudvModIp();
    }

}
