<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WebsiteTbSecurityEntity extends \Application\Entity\WebsiteTbSecurityEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seniId', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'senyStatus', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seniCreatedBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'sendCreatedDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'senvCreatedIp', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seniModBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'sendModDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'senvModIp', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seti');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seniId', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'senyStatus', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seniCreatedBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'sendCreatedDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'senvCreatedIp', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seniModBy', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'sendModDate', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'senvModIp', '' . "\0" . 'Application\\Entity\\WebsiteTbSecurityEntity' . "\0" . 'seti');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WebsiteTbSecurityEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSeniId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSeniId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeniId', array());

        return parent::getSeniId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenyStatus($senyStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenyStatus', array($senyStatus));

        return parent::setSenyStatus($senyStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenyStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenyStatus', array());

        return parent::getSenyStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeniCreatedBy($seniCreatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeniCreatedBy', array($seniCreatedBy));

        return parent::setSeniCreatedBy($seniCreatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeniCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeniCreatedBy', array());

        return parent::getSeniCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendCreatedDate($sendCreatedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendCreatedDate', array($sendCreatedDate));

        return parent::setSendCreatedDate($sendCreatedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendCreatedDate', array());

        return parent::getSendCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenvCreatedIp($senvCreatedIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenvCreatedIp', array($senvCreatedIp));

        return parent::setSenvCreatedIp($senvCreatedIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenvCreatedIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenvCreatedIp', array());

        return parent::getSenvCreatedIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeniModBy($seniModBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeniModBy', array($seniModBy));

        return parent::setSeniModBy($seniModBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeniModBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeniModBy', array());

        return parent::getSeniModBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendModDate($sendModDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendModDate', array($sendModDate));

        return parent::setSendModDate($sendModDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendModDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendModDate', array());

        return parent::getSendModDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenvModIp($senvModIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenvModIp', array($senvModIp));

        return parent::setSenvModIp($senvModIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenvModIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenvModIp', array());

        return parent::getSenvModIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeti(\Application\Entity\WebsiteTbSecurityEntityType $seti = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeti', array($seti));

        return parent::setSeti($seti);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeti()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeti', array());

        return parent::getSeti();
    }

}
