<form action="<?php echo $this->url('login'); ?>" method="post">
    <div class="row">
        <div class="small-12 columns">
            <label>Usuario
                <input type="text" name="user-email" placeholder="Ingrese su usuario" />
            </label>
        </div>
        <div class="small-12 columns">
            <label>Contraseña
                <input type="password" name="user-password" placeholder="Password" />
            </label>
            <button type="submit" class="button success">Entrar</button>
        </div>
    </div>
</form>