<?php

namespace Application\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebsiteTbPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteTbPersonRepository extends EntityRepository
{
}
